// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SampleCore.Entity
{
    public partial class Data
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Address { get; set; }
        [StringLength(10)]
        public string Phone { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Password { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Re_Type_Password { get; set; }
        public bool? Is_Delete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Create_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time_Stamp { get; set; }
    }
}